using System.Text;

namespace Crdt.Core;

/// <summary>
/// One operation generated by a replica.
/// </summary>
/// <remarks>
/// Every operation consumes a <see cref="ElementId.Seq"/>, inserts and deletes
/// alike, because PROJECT_SPEC.md §6 keys the operation log on
/// <c>(document_id, replica_id, seq)</c> for both and §7 requires the sequence
/// to be dense. The paper increments its counter only on insert, having no log.
/// </remarks>
/// <param name="Id">Identifies this operation, and for an insert the element it creates.</param>
public abstract record Operation(ElementId Id);

/// <summary>Creates one element immediately after <paramref name="Parent"/>'s position.</summary>
/// <remarks>
/// <para>
/// The placement fields come straight from Algorithm 1 lines 25–28 as amended by
/// Definition 6. <paramref name="RightOrigin"/> is carried only on right
/// children; on a left child it is absent, because FugueMax's reverse-right-origin
/// ordering applies only to the right-hand sibling list.
/// </para>
/// <para>
/// A <see langword="null"/> <paramref name="Parent"/> means the root sentinel. A
/// <see langword="null"/> <paramref name="RightOrigin"/> on a right child means
/// end-of-document — the paper's <c>end</c>. The two nulls are unrelated, which
/// is why <paramref name="Side"/> is needed to tell them apart.
/// </para>
/// </remarks>
public sealed record InsertOperation(
    ElementId Id,
    Rune Value,
    ElementId? Parent,
    Side Side,
    ElementId? RightOrigin) : Operation(Id);

/// <summary>Tombstones the element named by <paramref name="Target"/>.</summary>
/// <remarks>
/// The node is never removed: it may be an ancestor of live nodes, including
/// ones inserted concurrently (§5, and TPDS §4).
/// </remarks>
public sealed record DeleteOperation(ElementId Id, ElementId Target) : Operation(Id);
