// <auto-generated />
using System;
using Editor.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Editor.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EditorDbContext))]
    partial class EditorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Editor.Domain.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("Editor.Domain.DocumentMember", b =>
                {
                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.Property<Guid>("GrantedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("granted_by");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.HasKey("DocumentId", "UserId");

                    b.ToTable("document_members", (string)null);
                });

            modelBuilder.Entity("Editor.Domain.DocumentReplica", b =>
                {
                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<Guid>("ReplicaId")
                        .HasColumnType("uuid")
                        .HasColumnName("replica_id");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<long>("OperationCount")
                        .HasColumnType("bigint")
                        .HasColumnName("operation_count");

                    b.Property<DateTimeOffset?>("RetiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retired_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("DocumentId", "ReplicaId");

                    b.ToTable("document_replicas", (string)null);
                });

            modelBuilder.Entity("Editor.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<string>("OidcIssuer")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("oidc_issuer");

                    b.Property<string>("OidcSubject")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("oidc_subject");

                    b.HasKey("Id");

                    b.HasIndex("OidcIssuer", "OidcSubject")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Editor.Infrastructure.Persistence.DocumentOperationRow", b =>
                {
                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<Guid>("ReplicaId")
                        .HasColumnType("uuid")
                        .HasColumnName("replica_id");

                    b.Property<long>("Seq")
                        .HasColumnType("bigint")
                        .HasColumnName("seq");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("OpType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("op_type");

                    b.Property<Guid?>("ParentReplica")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_replica");

                    b.Property<long?>("ParentSeq")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_seq");

                    b.Property<bool>("RightOriginIsEnd")
                        .HasColumnType("boolean")
                        .HasColumnName("right_origin_is_end");

                    b.Property<Guid?>("RightOriginReplica")
                        .HasColumnType("uuid")
                        .HasColumnName("right_origin_replica");

                    b.Property<long?>("RightOriginSeq")
                        .HasColumnType("bigint")
                        .HasColumnName("right_origin_seq");

                    b.Property<long>("ServerSeq")
                        .HasColumnType("bigint")
                        .HasColumnName("server_seq");

                    b.Property<string>("Side")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("side");

                    b.Property<Guid?>("TargetReplica")
                        .HasColumnType("uuid")
                        .HasColumnName("target_replica");

                    b.Property<long?>("TargetSeq")
                        .HasColumnType("bigint")
                        .HasColumnName("target_seq");

                    b.Property<string>("Value")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("value");

                    b.HasKey("DocumentId", "ReplicaId", "Seq");

                    b.HasIndex("DocumentId", "ServerSeq");

                    b.ToTable("document_ops", (string)null);
                });

            modelBuilder.Entity("Editor.Infrastructure.Persistence.DocumentSnapshotRow", b =>
                {
                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<long>("ServerSeq")
                        .HasColumnType("bigint")
                        .HasColumnName("server_seq");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<byte[]>("State")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("state");

                    b.Property<string>("VersionVector")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("version_vector");

                    b.HasKey("DocumentId", "ServerSeq");

                    b.ToTable("document_snapshots", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
